logging:
  level: INFO
  loggers:
    com.plaid: DEBUG

plaidClientID: 5e483463b83f3800124fc1d6
plaidPublicKey: b52ac005757535f018e7cfb8da7803
plaidSecret: d7209cc545529b8616461450709a4a
plaidProducts: auth,transactions
plaidCountryCodes: US
plaidEnv: sandbox
